name: Get Random Characters
on:
  workflow_dispatch:
  schedule:
    - cron: 0 8,20 * * *

jobs:
  characters:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm run get-random-characters
      - run: |
          git config user.name iswilljr
          git config user.email iswilljr@gmail.com
          git add .
          git commit -m "add new random characters"
          git push
